### ISSUE TITLE
Example in docs is missing provider microsoftGraph declaration

### ISSUE THREAD

**Issue by slavizh** [microsoftgraph/msgraph-bicep-types#110]
The example here:
https://learn.microsoft.com/en-us/graph/templates/quickstart-create-bicep-interactive-mode?tabs=CLI
is missing provider microsoftGraph declaration to be added in the file which will cause to not see the resource providers for graph.

**Comment by dkershaw10** [comment]
@slavizh I can see it mentioned twice in the quickstart.  Maybe it's not prominent enough?

In the "Add a Microsoft Graph application group" it says:
In _main.bicep_, type `provider microsoftGraph`, to let the Bicep compiler know that you're including Microsoft Graph types.

At the end of "Make the managed identity an owner of the group resource", it says:
Your _main.bicep_ file should now look something like:
```bicep
provider microsoftGraph

param location string = resourceGroup().location
...
```

Please let me know what you think to make this more prominent, or resolve.

**Comment by slavizh** [comment]
Ok. I think than the misunderstanding mostly comes from here:
![image](https://github.com/microsoftgraph/msgraph-bicep-types/assets/11890856/12d46c69-4173-4443-a789-8c5f171d85d3)


The first one is just mentioned where the other example is shown as code block where you can do copy.

**Comment by dkershaw10** [comment]
Fair enough, and I can see where the confusion comes from.
I think we can make a simple change to update the 2nd screenshot to include the provider declaration.

**Comment by slavizh** [comment]
@dkershaw10 closing. I think now it is better. Thanks!
