### ISSUE TITLE
Link https://learn.microsoft.com/en-us/graph/templates/reference not accessable

### ISSUE THREAD

**Issue by slavizh** [microsoftgraph/msgraph-bicep-types#113]
The link posted here: https://learn.microsoft.com/en-us/graph/templates/concept-permissions-and-privileges
in sentence:
For Microsoft Graph Bicep resources, the least privileged permissions required for each resource type can be found in the [templates resource reference](https://learn.microsoft.com/en-us/graph/templates/reference).

does not work.

**Comment by dkershaw10** [comment]
Thanks - will fix. Changes were made to the reference docs, and it looks like it broke some links.

**Comment by dkershaw10** [comment]
@slavizh This link is now fixed.  Please reactivate if this is still broken for you.
