### ISSUE TITLE
Issue with existing AAD entities and read rights. 'Insufficient privileges to complete the operation.' 

### ISSUE THREAD

**Issue by HermenOtter** [microsoftgraph/msgraph-bicep-types#141]
**Bicep version**
v0.28.1.

**Resource and API version**
Which Microsoft.Graph resource and API version has the issue?
1.0

**Auth flow**
Is the deployment interactive (e.g. with a signed in user) or automated (e.g. with an application)?
Azure DevOps Service Connection with read rights on the AAD. (Through azure cli it is successful, not with the graph)

**Deployment details**
 "details": [

      {

        "code": "Forbidden",

        "message": "Insufficient privileges to complete the operation. Graph client request id: eed924f3-77ff-40d5-8b0d-0b75f198b8d9.",

        "target": "/resources/group"

      }

    ]

**Describe the bug**
The context is a service principal that has only read permissions on the graph. I expect this to be a common occurrence in companies with multiple teams. A strong feature of the msgraph provider would be to not imperatively retrieve the object ids of existing AAD entities and pass it through parameters. However, it seems to [require](https://learn.microsoft.com/en-us/graph/templates/reference/groups?view=graph-bicep-1.0) Read**Write** rights for the existing calls is by design or a bug? 

**To Reproduce**

```
provider microsoftGraph
resource group 'Microsoft.Graph/groups@v1.0' existing = {uniqueName: 'SomeGroupNameThatExistsInAAD'} 
```

**Additional context**
We provision the bicep through a deployment stack, executed by a service principal that is successful through the azure cli to fetch the same group.

**Comment by dkershaw10** [comment]
@HermenOtter - thanks for the bug report.  I assume that you granted your service principal `Group.Read.All` permission?
If so, this looks like a bug to me, but we'll investigate further.

**Comment by eketo-msft** [comment]
Stacks will not work for any Graph resources.  There is pending work on the Extensibility side to support Stacks e2e, but right now it does not properly perform OBO token exchange so the original subject we see is the Azure Deployments app (Stacks) and not the original subject which deploys the template via Stacks.

**Comment by dkershaw10** [comment]
@HermenOtter please validate whether this issue is present when you repeat the scenario **without** using deployment stacks.  If it doesn't repro, then this bug is part of our known issues/limitations.

**Comment by HermenOtter** [comment]
Thank you for the quick replies, I appreciate it. 

The service principal has Group.Read.All and was used for the following tasks:
1) `AzureCLI@2` with `az deployment group create` 
```
ERROR: {"code": "InvalidTemplateDeployment", "message": "The template deployment 'some-name' is not valid according to the validation procedure. The tracking id is '1f328b18-90af-42a7-9d7c-01e2e3e410e9'. See inner errors for details."}
 
Inner Errors:
{"code": "BadRequest", "target": "/resources/group", "message": "Cannot find requested resource."}
```

2) `AzureResourceManagerTemplateDeployment@3` with a resource group deployment. 

```
There were errors in your deployment. Error code: InvalidTemplateDeployment.
##[error]The template deployment 'somename-20240614-085337-e28e' is not valid according to the validation procedure. The tracking id is '8bf9b213-363c-4d7a-b2c3-6daab0883bea'. See inner errors for details.
##[error]Details:
##[error]BadRequest: Cannot find requested resource.
```
I left the tracking ids for debugging purposes.

**Comment by dkershaw10** [comment]
Not familiar with AzureResourceManagerTemplateDeployment, but it looks like the same error, which is not an authz error.
The extension (and Graph) is telling you that it cannot find the group resource with the `uniqueName` provided.

If you are trying to fetch an existing group from Graph that wasn't provisioned using Bicep, then chances are it doesn't have a uniqueName.  Please see [How to reference existing resources](https://learn.microsoft.com/graph/templates/how-to-reference-existing-resources?tabs=CLI) and [Uniquely named resources conceptual topic](https://learn.microsoft.com/graph/templates/concept-uniquely-named-resources).

Hope this helps

**Comment by HermenOtter** [comment]
You are correct. From stacks with "Insufficient privileges to complete the operation." to "Cannot find the requested resource" after reading the documentation you linked it must be the unique names not being backfilled. 

Thank you, I will post updates if I have any.

**Comment by HermenOtter** [comment]
If a team only has Group.Read.All I assume it still has a dependency on another team / elevated service principal to do the backfill of uniqueName, is there any chance that this uniqueName will be filled by default in the future? Do you have any suggestions for us to solve this situation?

**Comment by HermenOtter** [comment]
Thank you for your detailed write-up! I see the technical challenge here. Unfortunately it does not matter our names are actually unique, since we don't set the property. I think a naming policy rule is the best way forward. I will get back to you on this.

**Comment by dkershaw10** [comment]
@HermenOtter Is it OK to close this issue and open a new issue (new feature request) to "provide a default value for `uniqueName` on newly created groups" (possibly via a new naming policy rule in Group Settings for uniqueName)?  **NOTE**: it would be a sister team that would own reviewing this feature request and stack ranking it with other work.  It would be good to understand from other folks how important this feature is to them, so that it can be appropriately stack ranked..

**Comment by HermenOtter** [comment]
Yes, I think that is the right way forward. I want to stress on the importance of this, I can imagine there are many companies with DevOps teams that only have read access and their central team is not filling the uniqueName value, leaving a lot of unused potential on the table. I am now assuming you will create this feature request, please inform me if you think I should do that.

I want to thank you for your fast and detailed responses throughout this issue. Have a nice week!
