### ISSUE TITLE
Migrate ESRPCodeSigning to v5

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-bicep-types#162]
example https://github.com/microsoft/kiota-dotnet/pull/320

**Comment by dkershaw10** [comment]
@jason-dou please investigate

**Comment by jason-dou** [comment]
@baywet It looks like there's an auth issue and we need to wait for the strong naming key to be authorized? Do you know when it will be ready?

**Comment by baywet** [comment]
CP-401405 and CP-230012 which are the only ones you seem to be using from what I can see on this repo should already be authorized.
CP-233863-SN has been requested, but the deployment had an issue, the service team will attempt a new deployment on Tuesday (tomorrow)
Are there other codes you need access to?
