### ISSUE TITLE
Adding API permissions using Bicep as configured permissions, not other permissions granted

### ISSUE THREAD

**Issue by mikedzikowski** [microsoftgraph/msgraph-bicep-types#182]
First time posting here, so please let me know if I need to make any changes to my question or add more details. I am unable to add API permissions as configured using the Bicep resource Microsoft.Graph/oauth2PermissionGrants@v1.0. 

Example code used:

```
targetScope = 'tenant'

// entra-external-setup.bicep
extension microsoftGraph

param appName string = 'cspm'
param deployEnvironment string = 'lb'


var applicationRegistrationName = '${appName}-${deployEnvironment}-app-01'

var redirectUris = deployEnvironment == 'prod' 
  ? ['https://app.${appName}.io'] 
  : ['https://${applicationRegistrationName}.azurewebsites.net', 'https://localhost:44305']

resource microsoftGraphServicePrincipal 'Microsoft.Graph/servicePrincipals@v1.0' existing = {
  appId: '00000003-0000-0000-c000-000000000000'
}

resource applicationRegistration 'Microsoft.Graph/applications@v1.0' = {
  uniqueName: applicationRegistrationName
  displayName: applicationRegistrationName
  web: {
    redirectUris: [for item in redirectUris: '${item}/sigin-oidc']
    implicitGrantSettings: {
      enableIdTokenIssuance: true
    }
  }
  requiredResourceAccess: [
    {
     resourceAppId: microsoftGraphServicePrincipal.appId
     resourceAccess: [
       { 
         id: 'd07a8cc0-3d51-4b77-b3b0-32704d1f69fa', type: 'Scope' 
      }
     ]
    }
  ]
}

resource applicationRegistrationServicePrincipal 'Microsoft.Graph/servicePrincipals@v1.0' existing = {
  appId: applicationRegistration.appId
}

resource grants 'Microsoft.Graph/oauth2PermissionGrants@v1.0' = {
  clientId: applicationRegistrationServicePrincipal.id
  resourceId: microsoftGraphServicePrincipal.id
  consentType: 'AllPrincipals'
  scope: 'AccessReview.Read.All'
}
```

My goal is to use Bicep to add the API permissions, granted here:
![image](https://github.com/user-attachments/assets/709e5dcb-2f11-49e4-ac65-4628c494d859)

What am I missing? Thank you in advance!

**Comment by jason-dou** [comment]
@mikedzikowski Did you get any error when deploying the example template above? Could you share the deployment correlation Id, error message, MS Graph client request id, and timestamp? Were you using an interactive flow (with signed-in user) or automation (with application)?

**Comment by mikedzikowski** [comment]
Hi Jason,

Thank you for responding. 

The deployment is successful, however the permissions are not granted as expected. 

correlationId": "8da54681-b35e-4a62-bec4-969aca6932fa"
"timestamp": "2024-10-03T17:27:25.0031277Z"

resource microsoftGraphServicePrincipal 'Microsoft.Graph/servicePrincipals@v1.0' existing = {
  appId: '00000003-0000-0000-c000-000000000000'
}

This deployment was simply using Bicep that will later be expanded upon. The goal is to create a app registration, and apply API permissions and grant admin consent using bicep.

**Comment by mikedzikowski** [comment]
So a bit more testing, if admin consent is required - the permissions are set like so
![image](https://github.com/user-attachments/assets/ef21373c-b927-4ed2-85e8-18b04625b8fb)

if admin consent is not required they are configured properly and set.

**Comment by mikedzikowski** [comment]
This works:
// entra-external-setup.bicep
extension microsoftGraph

param appName string
param deployEnvironment string

targetScope = 'tenant'

var applicationRegistrationName = '${appName}-${deployEnvironment}-app-01'

var redirectUris = deployEnvironment == 'prod' 
  ? ['https://app.${appName}.io'] 
  : ['https://${applicationRegistrationName}.azurewebsites.net', 'https://localhost:44305']

resource microsoftGraphServicePrincipal 'Microsoft.Graph/servicePrincipals@v1.0' existing = {
  appId: '00000003-0000-0000-c000-000000000000'
}

resource applicationRegistration 'Microsoft.Graph/applications@v1.0' = {
  uniqueName: applicationRegistrationName
  displayName: applicationRegistrationName
  web: {
    redirectUris: [for item in redirectUris: '${item}/sigin-oidc']
    implicitGrantSettings: {
      enableIdTokenIssuance: true
    }
  }
  requiredResourceAccess: [
    {
     resourceAppId: microsoftGraphServicePrincipal.appId
     resourceAccess: [
       { id: '7427e0e9-2fba-42fe-b0c0-848c9e6a8182', type: 'Scope' } // offline_access
       { id: '37f7f235-527c-4136-accd-4a02d197296e', type: 'Scope' } // openid
       {id: 'e4c9e354-4dc5-45b8-9e7c-e1393b0b1a20', type: 'Scope'} // AuditLog.Read.All
     ]
    }
  ]
  appRoles: [
    {
      allowedMemberTypes: [
        'Application'
      ]
        description: 'Allows the app to read user profiles without a signed in user.'
        displayName: 'Read all users\' full profiles'
        id: '7ab1d382-f21e-4acd-a863-ba3e13f7da61'
        isEnabled: true
        value: 'Directory.Read.All'
    }
  ]
}

resource applicationRegistrationServicePrincipal 'Microsoft.Graph/servicePrincipals@v1.0' = {
  appId: applicationRegistration.appId
}

resource grants 'Microsoft.Graph/oauth2PermissionGrants@v1.0' = {
  clientId: applicationRegistrationServicePrincipal.id
  consentType: 'AllPrincipals'
  resourceId: microsoftGraphServicePrincipal.id
  scope: 'openid offline_access AuditLog.Read.All'
}
