### ISSUE TITLE
Unable to create oauth2PermissionGrants and use them in an application registration

### ISSUE THREAD

**Issue by dougclutter** [microsoftgraph/msgraph-bicep-types#207]
**Bicep version**
Using Azure CLI: Bicep CLI version 0.31.92 (b06509316a)

**Resource and API version**
extension 'br:mcr.microsoft.com/bicep/extensions/microsoftgraph/v1.0:0.1.8-preview'

**Auth flow**
Executed via Bicep CLI using the following command:
az deployment group create --resource-group az-rg-kecka1-01 --template-file main.bicep

**Deployment details**
We are creating an App Registration that has access to itself. To summarize, we are performing these steps:
```
resource appRegistration 'Microsoft.Graph/applications@v1.0' = {
  uniqueName: uniqueName
  displayName: displayName
}
resource appServicePrincipal 'Microsoft.Graph/servicePrincipals@v1.0' = {
  appId: appRegistration.appId
}
resource wdApiGrant 'Microsoft.Graph/oauth2PermissionGrants@v1.0' = {
  clientId: appServicePrincipal.id
  consentType: 'AllPrincipals'
  resourceId: appServicePrincipal.id
  scope: wdApiScope
}
resource addPermissionScopes 'Microsoft.Graph/applications@v1.0' = {
  uniqueName: uniqueName
  displayName: displayName
  api: {
    oauth2PermissionScopes: [ 
      {
        id: wdApiGrant.id
        adminConsentDescription: 'Access to secure APIs on WD API'
        adminConsentDisplayName: 'Access secured APIs on WD API site'
        type: 'Admin'
        isEnabled: true
        value: wdApiScope
      }
    ]
  }
}
```
The last step fails with this error message:
_Cannot convert the literal 'VV9MOdUDPUGZQCQZ_916FlVfTDnVAz1BmUAkGf_dehY' to the expected type 'Edm.Guid'._ 

So, we thought we needed to generate our own GUID.  We did it like this: `guid(wdApiGrant.id)`.  This allowed the last step to complete, but then it started failing when we tried adding `requiredResourceAccess`:
```
resource addRequiredResourceAccess 'Microsoft.Graph/applications@v1.0' = {
  uniqueName: uniqueName
  displayName: displayName
  requiredResourceAccess: [
    {
      resourceAppId: appId
      resourceAccess: [
        {
            id: guid(wdApiGrant.id)
            type: 'Scope'
        }
      ]
    }
  ]
}
```

This has been so frustrating because we have successfully created this configuration in the Portal and everything is working.  We used the existing manifest to guide our creation of the bicep files, but we keep hitting a wall.  How can we get this working?

Here is the detailed error message returned by the CLI:
{"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/c8dde15a-a34e-4149-8afb-d1adae70fa2d/resourceGroups/az-rg-kecka1-01/providers/Microsoft.Resources/deployments/main","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/c8dde15a-a34e-4149-8afb-d1adae70fa2d/resourceGroups/az-rg-kecka1-01/providers/Microsoft.Resources/deployments/WdApi-Development","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","target":"/subscriptions/c8dde15a-a34e-4149-8afb-d1adae70fa2d/resourceGroups/az-rg-kecka1-01/providers/Microsoft.Resources/deployments/WdApi-Development","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/c8dde15a-a34e-4149-8afb-d1adae70fa2d/resourceGroups/az-rg-kecka1-01/providers/Microsoft.Resources/deployments/addApiPermissionScopes","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","target":"/subscriptions/c8dde15a-a34e-4149-8afb-d1adae70fa2d/resourceGroups/az-rg-kecka1-01/providers/Microsoft.Resources/deployments/addApiPermissionScopes","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"","message":"{\"error\":{\"code\":\"BadRequest\",\"target\":\"/resources/addPermissionScopes\",\"message\":\"Cannot convert the literal 'VV9MOdUDPUGZQCQZ_916FlVfTDnVAz1BmUAkGf_dehY' to the expected type 'Edm.Guid'. Graph client request id: bcc4956f-33a0-446f-b350-b1466295e97d. Graph request timestamp: 2024-12-20T15:46:34Z.\"}}"}]}]}]}]}]}}

**Describe the bug**
We are trying to add oauth2PermissionScopes to an existing App Registration. 

**To Reproduce**
Run the deployment described above.

**Additional context**
(none)

**Comment by dkershaw10** [comment]
I'll try and debug this a bit further, but struggling to make sense of it.

**First thing** is why are you defining both `requiredResourceAccess` and `oauth2PermissionGrant`?
- `requiredResourceAccess` is what drives the consent experience - defining the permissions that an app **requires** to target resources. Generally more useful for multi-tenant applications, where other tenants "acquire" your app through a consent experience.
- `oauth2PermissionGrants` actually grants OAuth2 permission scopes defined by a resource to an app. You don't need to define `requiredResourceAccess` to be able to grant permissions.
  
Generally you don't need both - unless you have a specific scenario for this.

**Second thing** is it feels like you have a circular definition of the `id` going on between the grant and the OAuth2 scope definition that you are trying to grant. You're saying "make the id of the OAuth2 scope the same as the id of the grant of the OAuth2 scope".  However you can't grant the scope (to get its ID) unless you've already defined the scope with its ID.  Hopefully I'm making sense here.
TBH - I'm surprised this kind of worked, based on your script output.

I would:
1. define the scope's GUID upfront in a variable, and not tie it to the grant's ID.
2. Unless you have a good reason, don't define `requiredResourceAccess`

We have some samples that show resources exposing app roles, and client apps being granted app roles to call those resources.  However we don't have a Bicep example with OAuth2 scopes.  I can certainly add that.

**My bicep might look like:**

```Bicep
param wdApiScope string = 'adminScope'
var wdApiScopeID = guid('wdApiScope')

// App registration which exposes an API with an oauth2 scope called "adminScope"
resource appRegistration 'Microsoft.Graph/applications@v1.0' = {
  uniqueName: uniqueName
  displayName: displayName
  api: {
    oauth2PermissionScopes: [ 
      {
        id: wdApiScopeID
        adminConsentDescription: 'Access to secure APIs on WD API'
        adminConsentDisplayName: 'Access secured APIs on WD API site'
        type: 'Admin'
        isEnabled: true
        value: wdApiScope
      }
    ]
  }
}

resource appServicePrincipal 'Microsoft.Graph/servicePrincipals@v1.0' = {
  appId: appRegistration.appId
}

// grant the "adminScope" permission to the application
resource wdApiGrant 'Microsoft.Graph/oauth2PermissionGrants@v1.0' = {
  clientId: appServicePrincipal.id
  consentType: 'AllPrincipals'
  resourceId: appServicePrincipal.id
  scope: wdApiScope
}
```

**Comment by dougclutter** [comment]
> **First thing** is why are you defining both `requiredResourceAccess` and `oauth2PermissionGrant`?

We have a working App Registration that was setup via the Portal.  The manifest from the Portal includes both `requiredResourceAccess` and `oauth2PermissionGrant`, so we were just trying to replicate _that_ setup.

Thank you so much for explaining the difference between these two settings.  We'll try pressing ahead with only the `oauth2PermissionGrant` and see how that works.  Thanks!

**Comment by dkershaw10** [comment]
Thanks @dougclutter - let me know if you have any further issues and I'll be glad to help here.

**Comment by dougclutter** [comment]
Hi @dkershaw10 - took out the Required Resource stuff that was self-referential, but we're still getting this error:
```
{"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/c8dde15a-a34e-4149-8afb-d1adae70fa2d/resourceGroups/az-rg-kecka1-01/providers/Microsoft.Resources/deployments/main","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/c8dde15a-a34e-4149-8afb-d1adae70fa2d/resourceGroups/az-rg-kecka1-01/providers/Microsoft.Resources/deployments/WdApi-Development","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","target":"/subscriptions/c8dde15a-a34e-4149-8afb-d1adae70fa2d/resourceGroups/az-rg-kecka1-01/providers/Microsoft.Resources/deployments/WdApi-Development","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"","message":"{\"error\":{\"code\":\"BadRequest\",\"target\":\"/resources/updateAppRegistration\",\"message\":\"Cannot convert the literal 'VV9MOdUDPUGZQCQZ_916FlghjgJyQS9MgeXmfsmQumQ' to the expected type 'Edm.Guid'. Graph client request id: 1b9c356d-c396-48f5-bc31-3a254be1e842. Graph request timestamp: 2024-12-26T14:45:39Z.\"}}"}]}]}]}}
```

Here's the bicep file that failed:
```
extension microsoftGraphV1

param uniqueName string
param displayName string 
param hostName string
param additionalAuthorizedApplications object[] = []

var oidcSignIn = 'https://${hostName}/signin-oidc'
var oidcSignOut = 'https://${hostName}/signout-oidc'
var authenticationCallback = 'https://${hostName}/authentication/login-callback'
var wdApiScope = 'WdApi'
var wdApiScopeId = guid(uniqueName)
var microsoftGraphAppId = '00000003-0000-0000-c000-000000000000'
var graphUserReadAccess = {
	resourceAppId: microsoftGraphAppId
	resourceAccess: [
		{
			id: graphUserReadGrant.id
			type: 'Scope'
		}
	]
}
var preAuthorizedApplication = {
	appId: appRegistration.appId
	delegatedPermissionIds: [ wdApiScopeId ]
}
var preAuthorizedApplications = concat([ preAuthorizedApplication ], additionalAuthorizedApplications)

// This creates or finds the App Registration
resource appRegistration 'Microsoft.Graph/applications@v1.0' = {
	uniqueName: uniqueName
	displayName: displayName
	signInAudience: 'AzureADMyOrg'
	tags: [
		'webApi'
		'desktopApp'
		'webApp'
		'apiConsumer'
		'singlePageApp'
	]
}

// Get the Service Principal of the App Registration
resource appServicePrincipal 'Microsoft.Graph/servicePrincipals@v1.0' = {
	appId: appRegistration.appId
}

// Grant the wdApiScope to the App Registration
resource wdApiGrant 'Microsoft.Graph/oauth2PermissionGrants@v1.0' = {
	clientId: appServicePrincipal.id
	consentType: 'AllPrincipals'
	resourceId: appServicePrincipal.id
	scope: wdApiScope
}

// Get the Graph Service Principal
resource graphServicePrincipal 'Microsoft.Graph/servicePrincipals@v1.0' existing = {
	appId: microsoftGraphAppId
}
  
// Grant the User.Read scope to the App Registration
resource graphUserReadGrant 'Microsoft.Graph/oauth2PermissionGrants@v1.0'  = {
	clientId: appServicePrincipal.id
	consentType: 'AllPrincipals'
	resourceId: graphServicePrincipal.id
	scope: 'User.Read'
}

// This configures the App Registration.
// Note: it is a separate step because we need the AppId of the App Registration to complete its config.
resource updateAppRegistration 'Microsoft.Graph/applications@v1.0' = {
	uniqueName: uniqueName
	displayName: displayName
	requiredResourceAccess: [ graphUserReadAccess ]
	isFallbackPublicClient: true
	publicClient: {
		redirectUris: [ 'msal${appRegistration.appId}://auth' ]
	}
	identifierUris: [ 'api://${appRegistration.appId}' ]
	api: {
    oauth2PermissionScopes: [ 
      {
        id: wdApiScopeId
        adminConsentDescription: 'Access to secure APIs on WD API'
        adminConsentDisplayName: 'Access secured APIs on WD API site'
        type: 'Admin'
        isEnabled: true
        value: wdApiScope
      }
    ]
		preAuthorizedApplications: preAuthorizedApplications
	}
	spa: {
		redirectUris: [ authenticationCallback ]
	}
	web: {
		logoutUrl: oidcSignOut
		redirectUris: [ oidcSignIn ]
		implicitGrantSettings: {
			enableAccessTokenIssuance: false
			enableIdTokenIssuance: true
		}
	}
}

output preAuthorizedApplication object = preAuthorizedApplication
```

**Comment by dkershaw10** [comment]
@dougclutter the error shows that you are trying to set a non-guid value for a property that is expecting a GUID.  It looks like you are still doing what you were doing before - creating a grant and using the id of the grant (which is not a GUID) to try to create a `requiredResourceAccess` setting, that is not required.

This time you are using `graphUserReadGrant.id` (which is not a GUID) to set the ID for the `resourceAccess` in the `graphUserReadAccess` variable.

Again - if you are granting the permission there's no need to create a requiredResourceAccess for it.

Recommend fixing by:
1. Remove the `graphUserReadAccess` variable
2. Remove this line - `requiredResourceAccess: [ graphUserReadAccess ]` from the `updateAppRegistration` resource

**Comment by dougclutter** [comment]
@dkershaw10 - Thanks for all your help.  Took some more fiddling but we got it working.  Here are the files that worked:

**bicepconfig.json**
```
{
	"experimentalFeaturesEnabled": {
		"extensibility": true
	},
	// specify an alias for the version of the v1.0 dynamic types package you want to use
	"extensions": {
		"microsoftGraphV1": "br:mcr.microsoft.com/bicep/extensions/microsoftgraph/v1.0:0.1.8-preview"
	}
}
```
**main.bicep**
```
// Since the appRegistrations already exist in Entra, we manually set the uniqueNames to be the same as the Object Ids.
// If creating App Registration using bicep, just provide a unique value for the Unique Names.
// NOTE: Unique Names CANNOT be changed after they are set.

module development 'appRegistration.bicep' = {
    name: 'Development'
    params: {
        uniqueName: '_enter your unique name here_'
        displayName: '_enter your display name here_'
        hostName: 'localhost:7176'
    }
}

module developmentServer 'appRegistration.bicep' = {
    name: 'Development-Server'
    params: {
        uniqueName: '_enter your unique name here_'
        displayName: '_enter your display name here_'
        hostName: 'dev.example.com'
    }
}

module qat 'appRegistration.bicep' = {
    name: 'QAT'
    params: {
        uniqueName: '_enter your unique name here_'
        displayName: '_enter your display name here_'
        hostName: 'qat.example.com'
        additionalAppIds: [ development.outputs.appId, developmentServer.outputs.appId ]
    }
}
```
**appRegistration.bicep**
```
extension microsoftGraphV1

param uniqueName string
param displayName string 
param hostName string
param additionalAppIds string[] = []

var wdApiScope = 'MyAppScope'
var wdApiScopeId = guid(uniqueName)
var oauth2PermissionScopes = [ 
	{
		id: wdApiScopeId
		adminConsentDescription: 'Access to secure APIs on WD API'
		adminConsentDisplayName: 'Access secured APIs on WD API site'
		type: 'Admin'
		isEnabled: true
		value: wdApiScope
	}
]

// This creates or finds the App Registration
resource appRegistration 'Microsoft.Graph/applications@v1.0' = {
	uniqueName: uniqueName
	displayName: displayName
	signInAudience: 'AzureADMyOrg'
	isFallbackPublicClient: true
	tags: [
		'webApi'
		'desktopApp'
		'webApp'
		'apiConsumer'
		'singlePageApp'
	]
	api: {
    oauth2PermissionScopes: oauth2PermissionScopes
	}
	spa: {
		redirectUris: [ 'https://${hostName}/authentication/login-callback' ]
	}
	web: {
		logoutUrl: 'https://${hostName}/signout-oidc'
		redirectUris: [ 'https://${hostName}/signin-oidc' ]
		implicitGrantSettings: {
			enableAccessTokenIssuance: false
			enableIdTokenIssuance: true
		}
	}
}

// Get the Service Principal of the App Registration
resource appServicePrincipal 'Microsoft.Graph/servicePrincipals@v1.0' = {
	appId: appRegistration.appId
}

// Grant the wdApiScope to the App Registration
resource wdApiGrant 'Microsoft.Graph/oauth2PermissionGrants@v1.0' = {
	clientId: appServicePrincipal.id
	consentType: 'AllPrincipals'
	resourceId: appServicePrincipal.id
	scope: wdApiScope
}

// Get the Graph Service Principal
resource graphServicePrincipal 'Microsoft.Graph/servicePrincipals@v1.0' existing = {
	appId: '00000003-0000-0000-c000-000000000000'
}
  
// Grant the User.Read scope to the App Registration
resource graphUserReadGrant 'Microsoft.Graph/oauth2PermissionGrants@v1.0'  = {
	clientId: appServicePrincipal.id
	consentType: 'AllPrincipals'
	resourceId: graphServicePrincipal.id
	scope: 'User.Read'
}

var authorizationToSelf = {
	appId: appRegistration.appId
	delegatedPermissionIds: [ wdApiScopeId ]
}
var otherAuthorizedApplications = [for appId in additionalAppIds: {
	appId: appId
	delegatedPermissionIds: [ wdApiScopeId ]
}]

// This configures the App Registration.  It is a separate step because:
// 1) We need the AppId of the App Registration.
// 2) The oauth2PermissionScopes must exist before we can add preAuthorizedApplications which contain it.
resource updateAppRegistration 'Microsoft.Graph/applications@v1.0' = {
	uniqueName: uniqueName
	displayName: displayName
	publicClient: {
		redirectUris: [ 'msal${appRegistration.appId}://auth' ]
	}
	identifierUris: [ 'api://${appRegistration.appId}' ]
	api: {
    oauth2PermissionScopes: oauth2PermissionScopes
		preAuthorizedApplications: concat([ authorizationToSelf ], otherAuthorizedApplications)
	}
}

output appId string = appRegistration.appId
```
